-- auto Generated on 2019-11-16
-- DROP TABLE IF EXISTS person;
CREATE TABLE person(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
	age INT (11) NOT NULL DEFAULT -1 COMMENT 'age',
	sex VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'sex',
	`date` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'date',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'person';
